on:
  push:
     branches:
       - 'master'
       - 'dev'
name: CI
jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  build_docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo "::set-output name=repo_lower::$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')"
        id: repo
      - run: |
          chmod +x ./buildkeys.sh
          ./buildkeys.sh
        shell: bash
        env:
          MAPS_KEY: ${{ secrets.MAPS_KEY }}
          LOGIN_KEY: ${{ secrets.LOGIN_KEY }}
          GEO_KEY: ${{ secrets.GEO_KEY }}
          BACKEND: ${{ secrets.BACKEND }}
        name: Build Keys
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and push
        uses: docker/build-push-action@v1
        with:
          registry: docker.pkg.github.com
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ steps.repo.outputs.repo_lower }}/web
          tag_with_sha: true
          tag_with_ref: true

